name: Front

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  routine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://drager.github.io/wasm-pack/installer/init.sh -sSf | bash
      - name: Check
        run: npm ci && npm run check
        working-directory: gebeh-test-roms
